### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by cedriclombardot**

### CODE REVIEW

**Comment by RandomEtc** [comment]
Can you confirm that node still finds the correct file in the example? I wasn't aware that `require` worked that way, but if it does then I'll merge this change. Thanks!

**Comment by cedriclombardot** [comment]
Like for express depens if you already install in global or with a package.json in the example or if you want to use with the cloned version

**Comment by loktar00** [comment]
This fixed the issue I was having with it.

**Comment by RandomEtc** [comment]
Thanks for this / sorry for the delay. I fixed the README in 0db4e005ee5bf6086f5cf9490bfdf4b5f48bad8e as you suggested, but I left the example app the same in the repository. It's my intention that you would do:

```
git@github.com:RandomEtc/ejs-locals.git
cd ejs-locals
npm install
cd example
node app.js
```

If I change the require as you suggested then the app doesn't work this way. Please clarify if you think I'm mistaken.

**Pull request closed without merging**
